explain_code:
	@echo "This program will create the folders for your classess: ${FOLDERS}"
	@echo "plese input -  make generate  CN=[class Name] - to create the folders"
generate:
	@echo "Creating class folders for ${CN}..."
	mkdir ${CN}
	mkdir ${CN}/assigments
	mkdir ${CN}/lectures
	mkdir ${CN}/exams
	mkdir ${CN}/miscellaneous
clean:
	@echo "removing folders for ${CN}..."
	rm -r ${CM}/
