explain_code:
	@echo "This program will create the folders for your classess: ${FOLDERS}"
generate:
	@echo "Creating empty text files..."
	touch file-{1..10}.txt
clean:
	@echo "Cleaning up..."
	rm *.txt