explain_code:
	@echo "This program will create the folders for your classess: ${FOLDERS}"
	@echo "plese input -  MAKE generate  CN=[class Name] - to create the folders"
generate:
	@echo "Creating class folders for ${CN}..."
	mkdir ${CN}/assigments
	mkdir ${CN}/lectures
	mkdir ${CN}/exams
	mkdir ${CN}/miscellaneous
